import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { BotMessageSquare } from 'lucide-react';
import { redirect } from "next/dist/client/components/navigation";
import { getCurrentUser } from "../actions/getCurrentUser";
import Chat from "@/components/chat/Chat";
import Sidebar from '@/components/layout/Sidebar';
import Header from "@/components/layout/Header"
import { Button } from "@/components/ui/button"
import {
  Sheet,
  SheetContent,
  SheetTrigger,
} from "@/components/ui/sheet"
import '../globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function Layout({ children }: { children: React.ReactNode }) {
  const { data } = await getCurrentUser();
  
  if (!data.user) {
    redirect("/login");
  }

  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header user={data.user} />
        <div className="relative flex">
          <Sidebar />
          <main className="w-full">
            {children}
          </main>
        </div>
        <Sheet>
          <SheetTrigger asChild>
            <Button className="bottom-2 absolute right-0 mr-4" variant="outline">
              <BotMessageSquare />
              <span>AI Assistant</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="right">
            <Chat />
          </SheetContent>
        </Sheet>
      </body>
    </html>
  )
}
